os: windows

sudo: false

latex: false

language: r

r: release

warnings_are_errors: false

apt_packages:
  - libgdal-dev
  - libudunits2-dev
  - cargo
  - libpoppler-cpp-dev
  
cache:
  packages
  
git:
  depth: false
 
r_packages:
 
r_github_packages: 
- rensa/ggflags
- rstudio/DT

script:
  - Rscript deploy.r

notifications:
  email:
    recipients:
      - energystatistics@gov.scot
    on_success: change # default: change
    on_failure: always # default: always
